### ISSUE TITLE
New version avabile I have the link

### ISSUE THREAD

**Issue by ronzigames** [ac-1337/8-ball-pool-cheat#24]
https://easyvictory.shop/download.php

And I got banned because leaking the source :)))))

**Comment by ImsilverDev** [comment]
https://youtu.be/_IkHrVO9lWM make a clown of yourself

**Comment by ImsilverDev** [comment]
@ronzigames

**Comment by ronzigames** [comment]
What a noob staff :))). The leaked cheto is working in latest version.

https://media.discordapp.net/attachments/862645570807660565/995424304554586142/xCheto_8BP.mp4

**Comment by Mikhail-jax** [comment]
You just deleted the source code tf bro why

**Comment by husnainbalcy** [comment]
Send me a discord or telegram for free tool

**Comment by wesleyadriano13** [comment]
Can anyone send me some code to make it actually work so I need to update the offset?
